# Generated by Django 5.2 on 2025-05-03 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=100)),
                ('Puntos', models.IntegerField()),
                ('Nivel', models.IntegerField()),
                ('Objetivos', models.CharField(max_length=100)),
                ('Amistades', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_nivel', models.CharField(max_length=100)),
                ('Descripcion', models.TextField()),
                ('Puntos_Necesarios', models.IntegerField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nivel_usuario', to='home.usuario')),
            ],
        ),
    ]
