# Generated by Django 5.2 on 2025-05-05 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadoejercicio',
            name='usuario',
        ),
    ]
